name: My first action

on: push

jobs:
    clean_build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          run: echo "Checking out the code"
        - name: check out files
          uses: actions/checkout@v2
        - name: list the files
          run: ls -lt